plugins:
  - jekyll-seo-tag
theme: jekyll-theme-dinky
title: Kilcreggan Garage
description: Local Family Run Business With All Work Guaranteed
show_downloads: false
logo: https://github.com/TheLastDestroyer/kilcreggangarage.github.io/blob/master/assets/images/logo.png?raw=true
